### ISSUE TITLE
Improve maintainability by addressing static analysis issues

### ISSUE THREAD

**Issue by ccremer** [k8up-io/k8up#247]
## Summary

**As** K8up developer\
**I want** to fix the issues reported by static analysis\
**So that** I can improve maintainability of the code base

## Context

With linking CodeClimate to K8up, CodeClimate reported lots of issues that reduce maintainability. When setting up CodeClimate, we have ignored most of the issues, since that involves a too big of a change to do in one PR.

The [handler/schedule.go](https://github.com/vshn/k8up/blob/v1.0.0-rc2/handler/schedule.go#L82) code is rather lengthy and repetitive. It should be checked if and how this code could be optimized, e.g. by extracting the repetitive parts into a function.

The problem is that the action types (i.e. check, backup, archive, ...) currently do not share a common type or interface. This makes it a non-trivial effort. It's also the reason why this is it's own issue.

## Out of Scope

* New features
* Bugfixing
* Resolve all issues in one single PRs. Multiple PRs might be necessary for easier reviewing and step-by-step improvements.

## Further links

* #233 
* #242 
* [CodeClimage](https://codeclimate.com/github/vshn/k8up/issues)
  * [Duplication Issues](https://codeclimate.com/github/vshn/k8up/issues?category%5B%5D=duplication&status%5B%5D=&status%5B%5D=open&status%5B%5D=confirmed&engine_name%5B%5D=structure&engine_name%5B%5D=duplication)

## Acceptance criteria

* Given a CodeClimate report, when working on a K8up PR then the global number of issues should generally go down, not up. (Boy Scout Rule)
* Given the changes to the code, when reading the code, it should still be simple to understand it's purpose.
* Given the changes to the code, when observing k8up from the outside, it should not have changed it's behaviour.

## Implementation Ideas

* We might also want to tune certain checks or issues, but they should be conscious decisions, not out of lazyness.
* The duplication issues (see link above) may be a good place to begin

**Comment by cimnine** [comment]
See also https://github.com/vshn/k8up/pull/260#pullrequestreview-562761032

**Comment by ccremer** [comment]
Let's close this one, it's not really actionable
