### ISSUE TITLE
Document testing guide for developers

### ISSUE THREAD

**Issue by ccremer** [k8up-io/k8up#271]
## Summary

**As** K8up developer\
**I want** to know what the test strategy is\
**So that** I contribute K8up PRs with appropriate tests that ensures quality and maintainability.

## Context

This came out of discussion [about testing](https://github.com/vshn/k8up/discussions/231)

## Out of Scope

* Code Implementation. This is purely documentation

## Further links

* https://github.com/vshn/k8up/discussions/231

## Acceptance criteria

* Given K8up documentation, when I open documentation then I see navigation item(s) to K8up developer guide with subpages
* Given K8up documentation, when I read K8up developer guide, then the guide defines
  - the levels of tests: unit, integration, e2e tests
  - when to use which test level with which test framework
  - what metric is used to measure code quality
  - basic style and formatting for unit and integration test, using the given-when-then language
  - what a PR code reviewer should look for other than the code itself (e.g. good PR title, sensible commit messages and history)

## Implementation Ideas

* If applicable, provide reference or example test cases to support the definition

**Comment by Kidswiss** [comment]
Closing for now, we're planning to migrate from bats to kuttl.
