### ISSUE TITLE
Add e2e tests to test PreBackupPods

### ISSUE THREAD

**Issue by ccremer** [k8up-io/k8up#273]
## Summary

**As** K8up developer\
**I want** automated test case(s) that starts and waits for PreBackupPods\
**So that** I can verify that my change doesn't break K8up's PreBackupPod feature.

## Context

Add e2e tests that verifies scheduling of prebackup pods. Especially interesting is also the case of existing prebackup deployments or backup CR objects.

## Out of Scope

* Don't test the same application stack as described in the tutorial. As a first step, we just want to test K8up, not the tutorial

## Further links

- Test Framework: https://github.com/bats-core/bats-detik
- Related Discussion: #231
- current e2e tests: https://github.com/vshn/k8up/tree/master/e2e

## Acceptance criteria

all mentioned preconditions are scoped to local KIND-cluster

* Given a deployment of K8up operator and a PreBackupPod CR object, when a Schedule CR object with backup spec is created, then K8up starts the mentioned PreBackupPod and waits for completion before scheduling a backup.

## Implementation Ideas

* The PreBackupPod can be very simple, e.g. `echo $(date) >> myfile` (or any other verifiable content, but you get the gist)
* There may be 2 tests necessary: One in the case of inexisting prebackup deployment, another one for existing deployments.
* Do the test in its own namespace and leave the remaining artifacts. That should help with local development when trying to debug an issue.

**Comment by Kidswiss** [comment]
Closing for now, we're planning to migrate from bats to kuttl.
