### ISSUE TITLE
Automate Documentation Versioning

### ISSUE THREAD

**Issue by tobru** [k8up-io/k8up#513]
## Summary

**As** K8up Maintainer
**I want** automated documentation versioning
**So that** on K8up release the documentation is also released.

## Context

Documentation versioning is independent of the K8up code. The version of the documentation is specified in `docs/antora.yml`.
For each Major and Minor version a `docs/vMajor.Minor` branch has to be created and the `docs/antora.yml` adapted accordingly.
When a Patch release is made, the corresponding documentation branch needs to be updated accordingly (no new branch needs to be created for Patch releases).

## Out of Scope

* Antora CI Pipeline overhaul

## Further links

* https://docs.antora.org/antora/2.3/content-source-versioning-methods/
* https://git.vshn.net/vshn/k8up_documentation/

## Acceptance criteria

* Given a new Major or Minor version release of K8up, when the release tag is pushed, a docs branch gets created and the `docs/antora.yml` file patched accordingly
* Given a new Patch version release of K8up, when the release tag is pushed, the docs branch gets updated accordingly.

## Implementation Ideas

* GitHub Action doing it automatically

**Comment by cimnine** [comment]
It might also make sense to document how the documentation system now works and what conventions (like branch naming) it follows/expects.
