### ISSUE TITLE
Changelog Generator fails

### ISSUE THREAD

**Issue by cimnine** [k8up-io/k8up#520]
## Describe the bug

The release log generator does not work, see https://github.com/k8up-io/k8up/runs/3664001430.

## Additional context

The problem seems to be that 86d7667ef87f560b47c26d178d7b871b299fcaf0 is from a branch that originated in the _wrestic_ codebase and therefore – indeed – does not have a common ancestor to v1.2.0.

An idea might be to (temporarily?) add a tag to commit 663a0b1034d36005506a3a43f0390504a8563fbe (which is the commit where the wrestic code is merged into the K8up tree).

## Logs

```console
💥 Failed to retrieve - Invalid tag? - Because of: HttpError: No common ancestor between v1.2.0 and 86d7667ef87f560b47c26d178d7b871b299fcaf0^.
```

## Expected behavior

The changelog is generated without problems.

## To Reproduce

n/a

## Environment (please complete the following information):

- Image Version: n/a
- K8s Version: n/a
- K8s Distribution: n/a

## TODO

- [ ] Delete tag v1.99.99

**Comment by ccremer** [comment]
> An idea might be to (temporarily?) add a tag to commit 663a0b1 (which is the commit where the wrestic code is merged into the K8up tree).

If it helps, then yes. We can still manually cancel the release workflow for running the tag at 663a0b1 to avoid pushing images or making a release on GH

**Comment by cimnine** [comment]
I have tested the approach on a fork and it seems to work.

**Comment by tobru** [comment]
Let's close this one for now. We'll delete the `v1.99.99` once we've release 2.0.
