### ISSUE TITLE
Docs: Helm chart link broken

### ISSUE THREAD

**Issue by laserb** [k8up-io/k8up#524]
## Describe the bug

In the documentation https://k8up.io/k8up/1.2/index.html the link to the helm chart is broken

## Expected behavior

Links in the documentation should work.

**Comment by cimnine** [comment]
Thanks for reporting this! I'm not yet sure whether we fix the 1.2 version of the documentation. @tobru, wdyt? But the link will be fixed in the v2.x release for sure.

**Comment by tobru** [comment]
We can fix that link in the `docs/v1.2` branch. Just cherry-pick f683c283b32b52aa22b7a83db7decd3fb4ef7c22 into this docs branch.
