### ISSUE TITLE
Tell backupcommand in which container it should run

### ISSUE THREAD

**Issue by tobru** [k8up-io/k8up#566]
### Summary

**As** user of K8up
**I want** to control in which container of a Pod the backupcommand runs
**So that** I'm sure it runs in the correct container.

### Context

The [backupcommand](https://k8up.io/k8up/2.0/how-tos/application-aware-backups.html) runs by default in the first container of a Pod. This imposes that one has control over the order of containers in a Pod and makes it impossible to run a backupcommand in the correct container if the order doesn't match.

We should provide a way to control in which container the backupcommand gets executed.

### Implementation Ideas

An annotation which allows to specify the name of the container in which the backupcommand should be executed. E.g. `k8up.io/backupcommand-container`.

**Comment by vfolk30** [comment]
Hi ,
This feature is available now?

**Comment by Kidswiss** [comment]
Hi @vfolk30 

Yes the feature has been released yesterday with K8up 2.7. https://github.com/k8up-io/k8up/releases/tag/v2.7.0

So I'm closing here.
