### ISSUE TITLE
Helm chart for 2.1.0?

### ISSUE THREAD

**Issue by rparree** [k8up-io/k8up#574]
### Context

I wanted to use the 2.1.0 version using the helm chart. Any estimated time when this will be added to the chart repo?

And as a related question, can we in the meantime just use the `tag` chart value to pull images `v2.2.0`?

tx.,

**Comment by ccremer** [comment]
The K8up v2.1.0 is already released with this Helm chart release: https://github.com/appuio/charts/releases/tag/k8up-2.0.2

And yes, setting `image.tag` in the Helm values is sufficient to update K8up even if the latest chart version doesn't default to a newer K8up version.
