### ISSUE TITLE
Update to Restic 0.13.x

### ISSUE THREAD

**Issue by Kidswiss** [k8up-io/k8up#636]
### Summary

**As** a user
**I want** the most current restic version
**So that** I can profit from bugfixes and performance improvements

### Context

Restic 0.13.x was released not too long ago: https://github.com/restic/restic/releases/tag/v0.13.0

### Out of Scope

-

### Further links

- https://github.com/restic/restic/releases/tag/v0.13.1
- Renovate opened a PR: https://github.com/k8up-io/k8up/pull/628

### Acceptance Criteria

- K8up uses Restic 0.13.x

### Implementation Ideas

-

**Comment by ccremer** [comment]
Implemented by #628
