### ISSUE TITLE
K8up allows only to restore up to 3 pvcs

### ISSUE THREAD

**Issue by ThomasSteinbach** [k8up-io/k8up#639]
### Description

K8up only allows to create 3 restores in a namespace and starts deleting old ones (LIFO). That means you cannot restore more than 3 PVCs, as you can only restore one PVC per restore.

### Expected Behavior

* I could specify more than one PVC to restore per `Restore` definition
* Or I could create an arbitrary amount of `Restore`s

### Version of K8up

ghcr.io/k8up-io/k8up:v2.1.2

### Version of Kubernetes

v1.22.2+k3s2

### Distribution of Kubernetes

k3s

**Comment by Kidswiss** [comment]
Hi @ThomasSteinbach 

You should be able to control this behaviour with the `keepJob` field in the spec: https://k8up.io/k8up/2.1/references/api-reference.html#k8s-api-github-com-k8up-io-k8up-api-v1-restorespec
