### ISSUE TITLE
Ability to space out k8up backups in the same namespace (when there are many pre-backup-pods)

### ISSUE THREAD

**Issue by seanhamlin** [k8up-io/k8up#665]
### Summary

**As** "a platform administrator"\
**I want** "pre-backup-pods to have distributed start times in a namespace"\
**So that** "The backups are as quick as possible, and do not impact the platform"

### Context

See https://github.com/uselagoon/lagoon/issues/3143 for context. This is a single production namespace, with 30 database services in it. Lagoon generates a single k8up schedule

```
  backup:
    resources: {}
    schedule: 4 22 * * *
```

And 30 `PreBackupPod`s. All 30 pods schedule at the same time. This in turn causes the (shared) database cluster to experience higher than usual load, and k8s also does not appreciate 30 pods scheduling at the same time.

### Further links

 - https://github.com/uselagoon/lagoon/issues/3143

### Acceptance Criteria

It would be nice if there was a way to run only a single `PreBackupPod` at the one time in a given namespace, or insert some arbitrary delay between the PreBackupPod starts in a given namespace.

**Comment by Kidswiss** [comment]
Hi @seanhamlin 

Thanks for bringing this to our attention. 30 prebackup pods in a single namespace are quite a lot.

In your linked issue you're writing about spreading the pods over a time of 4 hours. That would also delay the backup by that amount. This also leaves a lot of room for things to change and go wrong. For example if other pods get created or deleted.

As a workaround we thought about a configurable delay between starting each pod. That should give you the ability to space out things as you see fit.

How does that sound to you?

**Comment by Kidswiss** [comment]
Hi @seanhamlin 

Do you have any feedback for my questions above?

**Comment by seanhamlin** [comment]
Thanks @Kidswiss, yes I would say having an option to stagger the `PreBackupPods` by even 10 seconds in a given `namespace`, would yield a much more stable backup process cluster wider.

**Comment by Kidswiss** [comment]
Hi  @seanhamlin 

We discussed this in the team and feel like this won't make sense once we've implemented #316.

Then you have the ability to create multiple schedules per namespace and do the spreading via those.
