### ISSUE TITLE
Why do we still have to add to the list without an annotation on the pvc?

### ISSUE THREAD

**Issue by acechef** [k8up-io/k8up#734]
### Description

Why do we still have to add to the list without an annotation on the pvc?
https://github.com/k8up-io/k8up/blob/adc974c236b5f27c7d33bddfb6321da40eb0498f/operator/executor/backup.go#L83

### Expected Behavior

no annotation skip the loop

### Version of K8up

v2.5.0

### Version of Kubernetes

v1.22

### Distribution of Kubernetes

native

**Comment by Kidswiss** [comment]
Hi @acechef 

I'm not quite sure if I get this issue right. Having to add the annotation to NOT backup the PVC is the currently intended behavior. https://github.com/k8up-io/k8up/issues/550 is about changing that.

Currently, K8up works by the Opt-Out principle. It will backup every RWX PVC it can find in the given namespace. To NOT backup a given RWX PVC in a namespace, you have to set the annotation.

Also see the docs:
https://k8up.io/k8up/2.3/how-tos/schedules.html (note at the very end)

**Comment by acechef** [comment]
> Having to add the annotation to NOT backup the PVC is the currently intended behavior

Sorry, I misunderstood. Close it
