### ISSUE TITLE
BACKUP_LOG_LEVEL is deprecated

### ISSUE THREAD

**Issue by srgvg** [k8up-io/k8up#754]
### Description

`https://github.com/k8up-io/k8up/blob/master/e2e/definitions/operator/values.yaml#L13` mentions `BACKUP_LOG_LEVEL`, however, that variable is deprecated, dating from `v1` as I was told.
Not sure if that is still needed here, but if not, better remove this last reference to it in the latest versions?

### Expected Behavior

n/a

### Version of K8up

master branch

### Version of Kubernetes

n/a

### Distribution of Kubernetes

n/a

**Comment by srgvg** [comment]
Additionally, there's the new `K8UP_DEBUG`, but it is not mentioned in the docs.

**Comment by Kidswiss** [comment]
AC:
* Remove the deprecated env var from the e2e test
* Clean up docs, so it contains the new variable and remove the old one
