### ISSUE TITLE
[Documentation Bug]: Search Finds Pages for All Versions

### ISSUE THREAD

**Issue by chloesoe** [k8up-io/k8up#787]
### Description

A search for e.g. "manual" leads to a result list for every version.
As a system engineer you are probably only interested in the results for the version you are using. 

The limitation to max 10 search results doesn't help either, like that the only results are from one page.

### Additional Context
![Selection_999(723)](https://user-images.githubusercontent.com/24636407/208643835-4af71a90-af0e-41be-bc96-5c347c3244c6.png)

### Expected Behavior

only pages for the desired version should be shown, or only the newest one.

### Steps To Reproduce

1. Go to https://k8up.io/k8up/2.5/index.html
2. enter "manual" in the search bar an hit enter
3. you'll get this list: 
    - [master] How to Restore a Backup
    - [2.2] How to Restore a Backup
    - [2.3] How to Restore a Backup
    - [2.5] How to Restore a Backup
    - [2.1] How to Restore a Backup
    - [2.4] How to Restore a Backup
    - [2.0] How to Optimize schedules across the cluster
    - [1.0] How to Optimize schedules across the cluster
    - [2.3] How to Optimize schedules across the cluster
    - [1.2] How to Optimize schedules across the cluster

### Version of K8up

v2.5

### Version of Kubernetes

not relevant

### Distribution of Kubernetes

not relevant

**Comment by Kidswiss** [comment]
@akosma Is it possible to limit the search to one tag?

**Comment by akosma** [comment]
Yes, you can add "2.6" for example in the search box and have only results from that tag appear.

**Comment by Kidswiss** [comment]
Thanks for the explanation. Closing here.

**Comment by akosma** [comment]
This issue will be tracked here: https://github.com/vshn/embedded-search-engine/issues/46
