### ISSUE TITLE
CRD link is not working 

### ISSUE THREAD

**Issue by vfolk30** [k8up-io/k8up#798]
### Description

I am installing k8up and during CRD installation its failing ,As link  is not working 

kubectl apply -f https://github.com/k8up-io/k8up/releases/download/k8up-4.0.2/k8up-crd.yaml -n k8up-operator 

_error: unable to read URL "https://github.com/k8up-io/k8up/releases/download/k8up-4.0.2/k8up-crd.yaml", server reported 404 Not Found, status code=404_

wget https://github.com/k8up-io/k8up/releases/download/k8up-4.0.2/k8up-crd.yaml

Not FOUND

### Logs

```shell
error: unable to read URL "https://github.com/k8up-io/k8up/releases/download/k8up-4.0.2/k8up-crd.yaml", server reported 404 Not Found, status code=404_
```

### Expected Behavior

Link should work for CRD installation

### Version of K8up

4.0.0

### Version of Kubernetes

1.21

### Distribution of Kubernetes

kubernetes

**Comment by Kidswiss** [comment]
Hi @vfolk30 

Thanks for pointing this out!

v4.0.2 of the helm chart has not yet been released. v4.0.1 should work though.

So could you try:
`kubectl apply -f https://github.com/k8up-io/k8up/releases/download/k8up-4.0.1/k8up-crd.yaml -n k8up-operator`

And see if it works for you?

**Comment by vfolk30** [comment]
HI @Kidswiss ,

Thank you for explanation. provided link is working.

I have a question, How to use custom CA root ca in k8up to work with   on-premises s3 compatible storage .

**Comment by Kidswiss** [comment]
Hi @vfolk30 

Custom CA is currently not supported. A similar discussion is held in this issue here: https://github.com/k8up-io/k8up/issues/792

**Comment by vfolk30** [comment]
Thank @Kidswiss .
You may close this and I will use QA forum for queries.
