### ISSUE TITLE
Job status not updated if pull and execution exceed 30 seconds

### ISSUE THREAD

**Issue by acechef** [k8up-io/k8up#830]
### Description
In my local environment, the network conditions are not very good. The time to pull the job image and execute the task often exceeds 30 seconds. Then, when re-entering the Provision function after 30 seconds, after executing `job.ReconcileJobStatus(ctx, jobKey, r.Kube, obj)`, the status of restore cr is still Started.

### Expected Behavior

I can receive the event when job was completed in reconcile func

### Version of K8up

v2.6.0

### Version of Kubernetes

v1.22

### Distribution of Kubernetes

native

**Comment by acechef** [comment]
I found the cause of the problem. The main reason is that when the restore job status is Started, the RequeueAfter operation is not performed.

In my local environment, the network conditions are not very good. The time to pull the job image and execute the task often exceeds 30 seconds. Then, when re-entering the Provision function after 30 seconds, after executing `job.ReconcileJobStatus(ctx, jobKey, r.Kube, obj)`, the status of restore cr is still Started.

However, the requeueAfter setting is not implemented in the following judgment, so the status of restore cr will not be updated even if the restore job has been completed.

The network environment of the e2e test should be good, so no problems were found.

**Comment by acechef** [comment]
I submitted a pr for this issue (the time of RequeueAfter is the same as that in backupcontroller), please review it

**Comment by Kidswiss** [comment]
Hi @acechef 

Thanks for the additional info. To be honest I was confused by your initial request, but your new comment makes things a lot clearer.
