### ISSUE TITLE
Older versions of the documentation should not show up by default

### ISSUE THREAD

**Issue by davidgubler** [k8up-io/k8up#872]
### Description

The current documentation mixes versions pretty badly. Examples:

https://www.google.com/search?channel=fs&client=ubuntu-sn&q=k8up+repoPasswordSecretRef
-> first search result points to version 0.1

https://k8up.io/k8up/2.7/references/object-specifications.html -> enter "repoPasswordSecretRef" in search field
-> first search result again points to version 0.1

### Expected Behavior

Google search results should primarily show the latest version and the internal search of the documentation should never switch between versions (that just doesn't make any sense).

I think the most obvious solution to this would be to configure the robots.txt file (or meta headers) to only index the latest version of the documentation.

I have no idea how the internal search of the documentation could be fixed.

(Generally I question the value of having the old documentation available. I understand the reasoning of that because somebody *might* have an old version of k8up or the operator and things might work differently there, but that would be better solved by having one single, unified documentation that includes hints like "xy worked differently up until operator version z").

### Version of K8up

irrelevant

### Version of Kubernetes

irrelevant

### Distribution of Kubernetes

irrelevant

**Comment by Kidswiss** [comment]
Ping @akosma 

This is somewhat related to #787. Is it possible to implement some of Gubi's suggestions?

**Comment by akosma** [comment]
There are two problems (related but slightly disconnected) mentioned here:
1. Google searches
2. Internal search engine

For the 1st one, a "robots.txt" like this one might do the trick:

```
User-agent: *
Allow: /k8up/
Allow: /k8up/2.7/
Disallow: /k8up/2.6/
Disallow: /k8up/2.5/
Disallow: /k8up/2.4/
Disallow: /k8up/2.3/
Disallow: /k8up/2.2/
Disallow: /k8up/2.1/
Disallow: /k8up/2.0/
Disallow: /k8up/1.2/
Disallow: /k8up/1.1/
Disallow: /k8up/1.0/
Disallow: /k8up/0.1/
```

For the second one, there's a bit of tweaking required in our https://github.com/vshn/embedded-search-engine/ project to make it more flexible.

**Comment by akosma** [comment]
The `robots.txt` specification has been included in the `playbook.yml` file of the deployment project on GitLab, and is generated by Antora automatically. It can be seen here: https://k8up.io/robots.txt
The version numbers of the `Allow` section must be tweaked manually, however.

**Comment by akosma** [comment]
The second part of the issue will be handled here: https://github.com/vshn/embedded-search-engine/issues/46

**Comment by akosma** [comment]
Closing this one but tracking issue on the other project.
