### ISSUE TITLE
Helm Chart: Please allow service account annotations

### ISSUE THREAD

**Issue by mkotsalainen** [k8up-io/k8up#875]
### Summary

They are needed so that we can add IRSA roles to the service account

### Context

You don't have support for annotations in your latest code

### Further links

https://github.com/k8up-io/k8up/blob/master/charts/k8up/templates/serviceaccount.yaml

**Comment by mkotsalainen** [comment]
Here's a PR For this: https://github.com/k8up-io/k8up/pull/876

I tried settings serviceAccount.create to false but that removes the ClusterRoleBinding so you'll need this if you want people to be able to use IRSA roles.

**Comment by Kidswiss** [comment]
Has been implemented via #877 and #879
