### ISSUE TITLE
Add global flag to skip all PVC backups

### ISSUE THREAD

**Issue by haasad** [k8up-io/k8up#878]
### Summary

**As** "cluster admin"\
**I want** "the option to skip automatic PVC backup"\
**So that** "I can use k8up for application-aware backup only"

### Context

We're using k8up extensively on clusters without RWX volumes for application-aware backups (db dumps etc.). With the introduction of RWO PVC backups by default in v2.6, we'd now have to annotate all existing (and future) RWO PVCs with `k8up.io/backup: "false"`. It would be nice to have a global flag to skip all PVC backups entirely to mimic the old behavior.

**Comment by tobru** [comment]
This is a duplicate of #550
