### ISSUE TITLE
Helm Chart 4.5.1 hasn't been released to repositories

### ISSUE THREAD

**Issue by timbrd** [k8up-io/k8up#959]
### Description

[Helm Chart 4.5.1](https://github.com/k8up-io/k8up/blob/master/charts/k8up/Chart.yaml#L9) hasn't been released to repositories. Artifacthub for example still lists version 4.5.0 as the current one: https://artifacthub.io/packages/helm/k8up/k8up

Please update the repositories.

### Expected Behavior

The current chart (4.5.1) should be available.

### Version of K8up

2.8.0

### Version of Kubernetes

1.29.3

### Distribution of Kubernetes

K3s

**Comment by Kidswiss** [comment]
Hi @timbrd 

The chart 4.5.1 hasn't been released at all yet.

**Comment by timbrd** [comment]
@Kidswiss Thanks for clarification. Do you know when 4.5.1 will be released? Is there a release schedule? I really would like to use the new option to backup only pvc which are annotated.

**Comment by Kidswiss** [comment]
K8up currently has no fixed release schedule.

We've planned in to create a new release this sprint. So 4.5.1 should come within 2 weeks.

**Comment by timbrd** [comment]
Thanks. I will wait another 2 weeks for a new release then.
