### ISSUE TITLE
Slack Channel (Permissions)?

### ISSUE THREAD

**Issue by tcurdt** [k8up-io/k8up#973]
### Description

I was trying to ask a few question. I wanted to check on Slack but...

![Screenshot 2024-05-27 at 18 38 45](https://github.com/k8up-io/k8up/assets/13697/b3097d73-2a78-4e53-bed7-7b6da8212d5e)

Is the link wrong?

### Additional Context

NA

### Logs

```shell
NA
```

### Expected Behavior

Let me join the slack channel.

### Steps To Reproduce

NA

### Version of K8up

NA

### Version of Kubernetes

NA

### Distribution of Kubernetes

NA

**Comment by tobru** [comment]
You should be in the CNCF Slack Workspace, if you aren't there yet, sign-up here: https://slack.cncf.io/
Then you'll kind the #k8up channel.

Does this work for you?

**Comment by tcurdt** [comment]
Works. Closing.

I've totally missed the link to https://slack.cncf.io/

Thanks!
